### ISSUE TITLE
power-splitter nur für custom-consumer

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/power-splitter#201]
nach meiner angestoßenen Diskussion [#3956](https://github.com/orgs/solectrus/discussions/3956) habe ich nun den power-splitter erstmalig eingefügt
und der Vorlage entsprechend angepasst
Solectrus läuft, aber der gewünschte Anzeigeeffekt (jeder Verbraucher zeigt PV/Netz Balken) bei den Verbrauchern bleibt aus.
In der power-splitter log sind auch ein paar Ungereimtheiten zu sehen

```
power-splitter-1  | Power Splitter for SOLECTRUS, Version develop, built at 2025-02-08 17:22:11 +0000
power-splitter-1  | Using Ruby 3.4.1 on platform aarch64-linux-musl
power-splitter-1  | Copyright (c) 2024-2025 Georg Ledermann <georg@ledermann.dev>
power-splitter-1  | https://github.com/solectrus/power-splitter
power-splitter-1  | 
power-splitter-1  | bundler: failed to load command: app.rb (app.rb)
power-splitter-1  | /power-splitter/lib/config.rb:22:in 'fetch': key not found: "INFLUX_HOST" (KeyError)
power-splitter-1  | 	from /power-splitter/lib/config.rb:22:in 'Config#initialize'
power-splitter-1  | 	from app.rb:28:in 'Class#new'
power-splitter-1  | 	from app.rb:28:in '<top (required)>'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/cli/exec.rb:59:in 'Kernel.load'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/cli.rb:452:in 'Bundler::CLI#exec'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/exe/bundle:28:in 'block in <top (required)>'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
power-splitter-1  | 	from /usr/local/bundle/gems/bundler-2.6.3/exe/bundle:20:in '<top (required)>'
power-splitter-1  | 	from /usr/local/bundle/bin/bundle:25:in 'Kernel#load'
power-splitter-1  | 	from /usr/local/bundle/bin/bundle:25:in '<main>'
```

die Wallbox und Wärmepumpe habe ich weggelassen

```yaml
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:develop
    environment:
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01
      - INFLUX_SENSOR_CUSTOM_POWER_02
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```
